name: Update and Publish Addon

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering as well

env:
  REDIS_URL: ${{ secrets.REDIS_URL }}
  REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          pip install upstash-redis

      # Fetch Updated Player Data
      - name: Fetch and Update Data File
        run: |
          python3 scripts/update_data.py
        continue-on-error: false

      # Install Lua syntax checker
      - name: Install Lua syntax checker
        run: |
          sudo apt-get update
          sudo apt-get install -y luacheck

      # Validate Addon Files
      - name: Validate Addon Files
        run: |
          luacheck src

      # Save updated Lua file as an artifact (optional)
      - name: Upload updated Lua file
        uses: actions/upload-artifact@v3
        with:
          name: Updated Lua File
          path: src/DungeonHonorData.lua

      # Package and Release
      # - name: Package and release
      #   uses: BigWigsMods/packager@v2
      #   with:
      #     args: -g retail
