name: Update and Publish Addon

on:
  schedule:
    - cron: '0 12,0 * * *'  # Runs daily at 6am & 6pm CST
  workflow_dispatch:  # Allow manual triggering as well

env:
  REDIS_URL: ${{ secrets.REDIS_URL }}
  REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          pip install upstash-redis

      # Fetch Updated Player Data
      - name: Fetch and Update Data File
        run: |
          python3 scripts/update_data.py
        continue-on-error: false

      # Install Lua and luarocks
      - name: Install Lua and luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks

      # Install luacheck via luarocks
      - name: Install luacheck
        run: |
          sudo luarocks install luacheck

      # Validate Addon Files
      - name: Validate Addon Files
        run: |
          luacheck src -g

      # Save DungeonHonor as an artifact (optional)
      - name: Upload updated Lua file
        uses: actions/upload-artifact@v3
        with:
          name: DungeonHonor
          path: src

      # Package and Release
      # - name: Package and release
      #   uses: BigWigsMods/packager@v2
      #   with:
      #     args: -g src
