name: Update and Publish Addon

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering as well

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch Updated Player Data
      - name: Fetch and Update Data File
        run: |
          python3 scripts/update_data.py  # Your Python script to update Data.lua

      # Validate Addon Files (optional)
      - name: Validate Addon Files
        run: |
          lua-syntax-check AddonFolder  # Replace with actual Lua linter or syntax checker

      # Package and Release
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail
