name: Update and Publish Addon

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering as well

jobs:
  update-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch Updated Player Data
      - name: Fetch and Update Data File
        run: |
          python3 scripts/update_data.py  # Your Python script to update Data.lua

      # Validate Addon Files (optional)
      - name: Validate Addon Files
        run: |
          lua-syntax-check AddonFolder  # Replace with actual Lua linter or syntax checker

      # Zip Addon Files
      - name: Zip Addon Files
        run: |
          zip -r DungeonHonor.zip AddonFolder

      # Upload to CurseForge
      - name: Upload to CurseForge
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          python3 scripts/upload_to_curseforge.py DungeonHonor.zip
