name: CurseForge Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Zip Addon
      run: |
        cd src  # Navigate to the src directory
        zip -r ../DungeonHonor.zip .  # Zip the contents of src, excluding the src folder itself

    - name: Upload to CurseForge
      env:
        API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      run: |
        pip install requests
        python - <<EOF
        import requests

        API_KEY = "${{ secrets.CURSEFORGE_API_KEY }}"
        PROJECT_ID = "your_project_id_here"
        FILE_PATH = "./DungeonHonor.zip"
        metadata = {
            "changelog": "Automated update via GitHub Actions.",
            "changelogType": "markdown",
            "displayName": "${{ github.ref_name }}",
            "gameVersions": [12345],
        }
        url = f"https://api.curseforge.com/v1/projects/{PROJECT_ID}/upload-file"
        headers = {"x-api-key": API_KEY}

        with open(FILE_PATH, "rb") as file:
            files = {"file": file}
            response = requests.post(url, headers=headers, data=metadata, files=files)

        if response.status_code == 200:
            print("Addon uploaded successfully!")
        else:
            print(f"Failed to upload: {response.status_code}, {response.text}")
        EOF
